# Generated by Django 3.2.14 on 2022-08-20 20:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=4, verbose_name='Collection Name')),
                ('collection_number', models.CharField(max_length=4, verbose_name='Collection Number')),
                ('collection_color', models.CharField(max_length=7, verbose_name='Collection Color (HEX)')),
                ('collection_slug', models.CharField(max_length=8, verbose_name='Collection Slug (Link)')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
                ('address1', models.CharField(max_length=150, verbose_name='Address Line 1')),
                ('address2', models.CharField(max_length=150, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('state', models.CharField(max_length=150, verbose_name='State')),
                ('zip_code', models.CharField(max_length=10, verbose_name='ZIP Code')),
                ('country', models.CharField(default='India', max_length=50, verbose_name='Country')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('order', models.CharField(max_length=10000, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('price', models.CharField(max_length=5, verbose_name='Price')),
                ('featured', models.BooleanField(verbose_name='Featured')),
                ('img1', models.ImageField(upload_to='media', verbose_name='Image 1')),
                ('img2', models.ImageField(upload_to='media', verbose_name='Image 2')),
                ('img3', models.ImageField(upload_to='media', verbose_name='Image 3')),
                ('male', models.BooleanField(verbose_name='Male Clothing')),
                ('female', models.BooleanField(verbose_name='Female Clothing')),
                ('description', models.CharField(max_length=500, verbose_name='Product Description')),
                ('product_id', models.CharField(default=uuid.uuid4, editable=False, max_length=128, primary_key=True, serialize=False, verbose_name='Product ID')),
                ('product_sku', models.CharField(default='UOsMRnHs', max_length=20, verbose_name='Product SKU')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strada1949.collection')),
            ],
        ),
    ]
