# Generated by Django 3.2.14 on 2022-08-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strada1949', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=True, verbose_name='Order Completed'),
            preserve_default=False,
        ),
    ]
