# Generated by Django 3.2.14 on 2022-08-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strada1949', '0002_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.BooleanField(null=True, verbose_name='Order Completed'),
        ),
    ]
